name: Test

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: check-update
  cancel-in-progress: false

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: tueda/check-upstream-action-dev@main
        with:
          upstream-repository: tueda/check-upstream-action-test1
